### ISSUE TITLE
Bundler helper prelude is emitted after its call site in the SSR chunk, so the worker throws __exportAll is not a function

### ISSUE THREAD

**Issue by mshykov** [nitrojs/nitro#4605]
## Environment

- nitro 3.0.260603-beta (also reproduced on 3.0.260610-beta)
- vite 8.2.2
- @tanstack/react-start 1.168.49
- @tanstack/react-router 1.170.32
- react 19.2.8
- wrangler 4.98.0
- bun 1.3.14, node v26.8.1
- macOS arm64
- preset: `nitro({ defaultPreset: "cloudflare-module" })`, added to the Vite plugin list for `command === "build"` only

## How to reproduce

The trigger is having `@clerk/tanstack-react-start` in the SSR module graph. On a TanStack Start app that builds and runs correctly:

1. `bun add @clerk/tanstack-react-start` (1.5.9)
2. In `src/routes/__root.tsx`, wrap the shell in `<ClerkProvider publishableKey="pk_test_probe">`. Nothing else. No middleware, no server-side Clerk import, no real keys.
3. `rm -rf .output node_modules/.vite && bun run build`
4. `wrangler dev --config .output/server/wrangler.json` and request `/`

Before step 1 and 2, the same project builds a chunk where the helper is declared at line 11 and used at line 1640, and the worker serves normally. After, the declaration moves below the call site.

I have not reduced this to a fresh scaffold, so I cannot say whether Clerk is the only package that triggers it or whether it is one of a class of module shapes. Clerk is what surfaced it for us.

## Comparison: same code built without the nitro plugin

Removing only the `nitro(...)` entry from the Vite plugin list, and building with TanStack Start alone, produces `dist/server/server.js` plus `dist/client/`. In that output the helper is not inlined into the entry chunk. It lives in a shared chunk and is imported:

```js
// dist/server/assets/server-Bqn8B5z-.js
import { U as __exportAll } from "./router-DKPZmNT_.js"
```

`dist/server/assets/router-DKPZmNT_.js` declares it at line 17 and uses it at line 2843, so the order is correct.

Running that output under wrangler (`main: dist/server/server.js`, `assets: { directory: "dist/client" }`, `compatibility_flags: ["nodejs_compat"]`) works with the same Clerk code in place: `/` returns a 307 to the app's own normalised search params, and `/settings` returns 200. No errors.

So the application code and Clerk are fine on Workers. The difference is in how the nitro build step places the helpers.

## What I ruled out

- Not caused by stale build output. Reproduced after `rm -rf .output node_modules/.vite`.
- Not caused by missing or malformed Clerk keys. Reproduced with both keys set, with only one set, and with none.
- Not caused by `clerkMiddleware()`. Removing it from the request middleware entirely still reproduces, because `ClerkProvider` alone keeps Clerk in the SSR graph.
- Not fixed by changing import order in the server entry.
- Not fixed by `build.rollupOptions.output.manualChunks` isolating `@clerk/*` into its own chunk.
- Not fixed by nitro 3.0.260610-beta. nitro 3.0.260903-beta fails earlier, during `writeWranglerConfig` in `_presets.mjs`, so I could not test it.

## Expected

Either the helper prelude is emitted at the top of the chunk that uses it, or it is imported from a shared chunk the way the plain Vite build does it. A build that produces a worker which throws on its first request should not report success.

## What happens

`bun run build` succeeds. Running the output with `wrangler dev --config .output/server/wrangler.json` and requesting `/` gives:

```
✘ [ERROR] TypeError: __exportAll is not a function
      at null.<anonymous> (.output/server/_ssr/server-DChvPAdW.mjs:1637:38)
[wrangler:info] GET / 500 Internal Server Error
```

The generated chunk is 4504 lines. At line 1637:

```js
var server_exports = /* @__PURE__ */ __exportAll({
	createServerEntry: () => createServerEntry,
	default: () => server_default
});
```

At line 1712, 75 lines later:

```js
var __exportAll = (all, no_symbols) => {
	let target = {};
	for (var name in all) __defProp(target, name, {
	...
```

Line 1707 onward, in order: `var authEnabled`, `var __defProp`, `var __getOwnPropDesc`, `var __getOwnPropNames`, `var __hasOwnProp`, `var __exportAll`. So the helpers are placed after a piece of application code, not at the top of the chunk.

There is no import of the helper in that chunk:

```
$ grep -c "import.*__exportAll" .output/server/_ssr/server-DChvPAdW.mjs
0
```

## Summary

With the `cloudflare-module` preset, the built server chunk calls `__exportAll(...)` at line 1637 but declares it at line 1712. Because the declaration uses `var`, hoisting makes the binding `undefined` at the point of the call, and the worker throws on the first request. Every request returns 500. The build itself reports success.

The whole helper prelude (`__defProp`, `__getOwnPropDesc`, `__getOwnPropNames`, `__hasOwnProp`, `__exportAll`) ends up in the middle of the chunk instead of at the top, directly after application code.

### Logs

```sh

```

**Comment by mshykov** [comment]
Some follow-up: related issues, a sharper look at the mechanism, and the results of trying to reduce this to a nitro-only reproduction.

## Related issues

**#4113** is the closest, and I think it is the same area rather than the same bug. It is also TanStack Start on nitro v3, also the server build, and the failures there are all bundler interop helpers that are not usable at module-evaluation time: `Cannot destructure property '__extends' from null or undefined`, `Class extends value #<Object> is not a constructor`, and one report with `pg`.

The difference is what is wrong with the helper. In #4113 the helper resolves to `undefined`/`null` — the interop shape is wrong. Here the helper is present and correct, it is simply **declared after the code that calls it**, in the same file:

```
server-DChvPAdW.mjs:1637   var server_exports = __exportAll({ ... });   // call
server-DChvPAdW.mjs:1712   var __exportAll = (all, no_symbols) => {     // declaration
```

75 lines apart, `var`, so it hoists as `undefined` and the call throws. That is an ordering fault, not an interop one. Same family, different failure.

**#3666** (`inherits4 is not a function`) looks similar from the error text but is client-side, in the Vite dev dep-optimizer, inside `@react-pdf/renderer`'s own bundle. I do not think it is the same thing.

## The helper set, and how nitro uses it internally

`__exportAll` is not a one-off. It comes from `nitro/dist/_common.mjs`, which exports the CJS interop set:

```js
export { __commonJSMin, __exportAll, __require, __toESM };
```

Those are the same helpers the failures in #4113 are about.

What stands out is that inside nitro's own dist these are **imported**, not inlined. For example `nitro/dist/_libs/plugin-inject.mjs`:

```js
import { __exportAll } from "../_common.mjs";
var es_exports = /* @__PURE__ */ __exportAll({ default: () => inject });
```

In the broken application output they are inlined into the consuming chunk instead, and placed after the call site. The chunk has no import of the helper at all:

```
$ grep -c "import.*__exportAll" .output/server/_ssr/server-DChvPAdW.mjs
0
```

Line 1707 onward in that chunk reads, in order: `var authEnabled` (application code), then `var __defProp`, `__getOwnPropDesc`, `__getOwnPropNames`, `__hasOwnProp`, `__exportAll`. So the whole prelude is emitted mid-file, after application code, rather than at the top or imported from a shared chunk.

For comparison, the same application built without the nitro plugin — TanStack Start's own output — imports it across chunks and works:

```js
// dist/server/assets/server-Bqn8B5z-.js
import { U as __exportAll } from "./router-DKPZmNT_.js"
```

where `router-DKPZmNT_.js` declares it at line 17 and uses it at line 2843.

## Trying to reduce it to nitro only

You asked for a nitro-only reproduction on #4113. I tried to build one and did not manage it. The negative results seem worth having, since they narrow where to look:

1. Bare `vite` + `nitro({ defaultPreset: "cloudflare-module" })` with a trivial server entry: **none of these helpers appear in the output at all**.
2. Adding a namespace import (`import * as x from "./entry"`) of a local ESM module, including using the namespace dynamically via `Object.keys(...)`: still no helpers. Rolldown reduces it away.
3. Adding a local CommonJS file (`.cjs`) that is namespace-imported: still no helpers. The CJS→ESM conversion happens without them.
4. Adding a real CJS npm dependency — `pg`, since that is what one report on #4113 hit: still no helpers.

So on a plain nitro app I could not get `_common.mjs` to be pulled in at all. That suggests the helpers arrive through something in the framework plugin's path rather than through ordinary CJS interop, which might be why a nitro-only reduction has been hard for everyone on #4113 too.

## What does reproduce

TanStack Start + nitro `cloudflare-module`. The trigger is narrow, and I isolated it to one variable: take the app in a state where the server chunk is correct (helper declared at line 11, used at 1640), add **nothing but** `<ClerkProvider>` from `@clerk/tanstack-react-start` in `__root.tsx` — no middleware, no server-side Clerk import, a fake publishable key — and the declaration moves below the call site. Removing it puts it back.

Versions: nitro `3.0.260603-beta` and `3.0.260610-beta` both reproduce. `3.0.260903-beta` fails earlier, inside `writeWranglerConfig`, so I could not test it. vite 8.2.2, @tanstack/react-start 1.168.49, wrangler 4.98.0.

Also ruled out, in case it saves anyone time: not stale build output (reproduced after `rm -rf .output node_modules/.vite`), not import order in the server entry, and not fixed by `build.rollupOptions.output.manualChunks` isolating the offending package into its own chunk.

## Note on our own case

We are no longer blocked — we removed the nitro plugin and deploy TanStack Start's own output to Cloudflare Workers directly, which avoids the fault entirely. So this is not urgent for us. I am adding the detail because #4113 has been open since March with several people pinning old nightlies, and the ordering angle does not seem to have been looked at yet.
