### ISSUE TITLE
Preview command for Node preset is missing serverDir substitution

### ISSUE THREAD

**Issue by thasmo** [nitrojs/nitro#3480]
### Environment

Node 22.17.0
Nitro 2.12.0
Nuxt 4.0.0
Windows WSL2

### Reproduction

Run `nuxt build`, it creates `.output/nitro.json` with the wrong preview command.

### Describe the bug

Upgrading from Nuxt v3 to v4 and running `nuxt build` and then `nuxt build` results in an error:

```sh
ℹ Starting preview command: node {{ output.serverDir }}/index.mjs                                                                                                                                           
node:internal/modules/cjs/loader:1404
  throw err;
  ^
Error: Cannot find module '/home/thasmo/projects/project-1/.output/{{'
```

### Additional context

nitro.json:
```json
{
  "date": "2025-07-16T08:05:07.563Z",
  "preset": "node-server",
  "framework": {
    "name": "nuxt",
    "version": "4.0.0"
  },
  "versions": {
    "nitro": "2.12.0"
  },
  "commands": {
    "preview": "node {{ output.serverDir }}/index.mjs"
  },
  "config": {}
}
```

**Comment by Larscode-io** [comment]
I have the same issue on MacOS

- Operating System: `Darwin`
- Node Version:     `v22.15.1`
- Nuxt Version:     `4.0.0`
- CLI Version:      `3.26.2`
- Nitro Version:    `2.12.0`
- Package Manager:  `npm@11.4.2`
- Builder:          `-`
- User Config:      `modules`, `plugins`, `$development`, `$production`, `ssr`, `devtools`, `app`, `css`, `content`, `runtimeConfig`, `build`, `devServer`, `compatibilityDate`, `vite`, `i18n`, `server`
- Runtime Modules:  `@nuxt/content@3.6.3`, `@nuxtjs/i18n@9.5.6`
- Build Modules:    `-`

**Comment by Norbiros** [comment]
Regression caused by https://github.com/nitrojs/nitro/pull/3388

**Comment by pi0** [comment]
Thanks for reporting the issue.

`nuxi preview` needs to support the new substitution pattern (added by #3388) when reading in preview command. 

In the meantime, i suggest following CLI hint for preview `node .output/server/index.mjs`

**Comment by pi0** [comment]
Will be solved by #3481 in next patch / nightly 👍🏼
